name: jsd

channels:
    - defaults
    - conda-forge

dependencies:
    - python=3.8
    - numpy
    - pandas
    - matplotlib
    - tqdm
    - seaborn
    - scikit-learn
    - yaml
    - jinja2=3.1.2
    - pip
    - pip:
        - mir-eval==0.5
